//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynoDs.Core.Error.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorRepository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorRepository() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SynoDs.Core.Error.Resources.ErrorRepository", typeof(ErrorRepository).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string Base100 {
            get {
                return ResourceManager.GetString("Base100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter of API, method or version.
        /// </summary>
        public static string Base101 {
            get {
                return ResourceManager.GetString("Base101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested API does not exist.
        /// </summary>
        public static string Base102 {
            get {
                return ResourceManager.GetString("Base102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested method does not exist.
        /// </summary>
        public static string Base103 {
            get {
                return ResourceManager.GetString("Base103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested version does not support the functionality.
        /// </summary>
        public static string Base104 {
            get {
                return ResourceManager.GetString("Base104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logged in session does not have permission.
        /// </summary>
        public static string Base105 {
            get {
                return ResourceManager.GetString("Base105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timeout.
        /// </summary>
        public static string Base106 {
            get {
                return ResourceManager.GetString("Base106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session interrupted by duplicate login.
        /// </summary>
        public static string Base107 {
            get {
                return ResourceManager.GetString("Base107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed.
        /// </summary>
        public static string DS400 {
            get {
                return ResourceManager.GetString("DS400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of tasks reached.
        /// </summary>
        public static string DS401 {
            get {
                return ResourceManager.GetString("DS401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination denied.
        /// </summary>
        public static string DS402 {
            get {
                return ResourceManager.GetString("DS402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination does not exist.
        /// </summary>
        public static string DS403 {
            get {
                return ResourceManager.GetString("DS403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid task id.
        /// </summary>
        public static string DS404 {
            get {
                return ResourceManager.GetString("DS404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid task action.
        /// </summary>
        public static string DS405 {
            get {
                return ResourceManager.GetString("DS405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter of file operation.
        /// </summary>
        public static string FS400 {
            get {
                return ResourceManager.GetString("FS400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error of file operation.
        /// </summary>
        public static string FS401 {
            get {
                return ResourceManager.GetString("FS401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is too busy.
        /// </summary>
        public static string FS402 {
            get {
                return ResourceManager.GetString("FS402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user does this file operation.
        /// </summary>
        public static string FS403 {
            get {
                return ResourceManager.GetString("FS403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid group does this file operation.
        /// </summary>
        public static string FS404 {
            get {
                return ResourceManager.GetString("FS404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user and group does this file operation.
        /// </summary>
        public static string FS405 {
            get {
                return ResourceManager.GetString("FS405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t get user/group information from the account server.
        /// </summary>
        public static string FS406 {
            get {
                return ResourceManager.GetString("FS406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not permitted.
        /// </summary>
        public static string FS407 {
            get {
                return ResourceManager.GetString("FS407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such file or directory.
        /// </summary>
        public static string FS408 {
            get {
                return ResourceManager.GetString("FS408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-supported file system.
        /// </summary>
        public static string FS409 {
            get {
                return ResourceManager.GetString("FS409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect internet-based file system (ex: CIFS).
        /// </summary>
        public static string FS410 {
            get {
                return ResourceManager.GetString("FS410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only file system.
        /// </summary>
        public static string FS411 {
            get {
                return ResourceManager.GetString("FS411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename too long in the non-encrypted file system.
        /// </summary>
        public static string FS412 {
            get {
                return ResourceManager.GetString("FS412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename too long in the encrypted file system.
        /// </summary>
        public static string FS413 {
            get {
                return ResourceManager.GetString("FS413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        public static string FS414 {
            get {
                return ResourceManager.GetString("FS414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk quota exceeded.
        /// </summary>
        public static string FS415 {
            get {
                return ResourceManager.GetString("FS415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No space left on device.
        /// </summary>
        public static string FS416 {
            get {
                return ResourceManager.GetString("FS416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input/output error.
        /// </summary>
        public static string FS417 {
            get {
                return ResourceManager.GetString("FS417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal name or path.
        /// </summary>
        public static string FS418 {
            get {
                return ResourceManager.GetString("FS418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal file name.
        /// </summary>
        public static string FS419 {
            get {
                return ResourceManager.GetString("FS419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal file name on FAT file system.
        /// </summary>
        public static string FS420 {
            get {
                return ResourceManager.GetString("FS420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device or resource busy.
        /// </summary>
        public static string FS421 {
            get {
                return ResourceManager.GetString("FS421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such task of the file operation.
        /// </summary>
        public static string FS599 {
            get {
                return ResourceManager.GetString("FS599", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such account or incorrect password.
        /// </summary>
        public static string Login400 {
            get {
                return ResourceManager.GetString("Login400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest account disabled.
        /// </summary>
        public static string Login401 {
            get {
                return ResourceManager.GetString("Login401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account disabled.
        /// </summary>
        public static string Login402 {
            get {
                return ResourceManager.GetString("Login402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string Login403 {
            get {
                return ResourceManager.GetString("Login403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        public static string Login404 {
            get {
                return ResourceManager.GetString("Login404", resourceCulture);
            }
        }
    }
}
